# 基础配置
CONFIG_ZMK_KEYBOARD=y
CONFIG_ZMK_BLE=y
CONFIG_ZMK_BLE_CENTRAL=y
CONFIG_ZMK_BLE_PERIPHERAL=n
CONFIG_ZMK_HID=y
CONFIG_ZMK_HID_USB=y

# USB 配置
CONFIG_USB=y
CONFIG_USB_DEVICE=y
CONFIG_USB_HID=y
CONFIG_USB_DEVICE_STACK=y

# 蓝牙配对
CONFIG_BT_MAX_CONN=1
CONFIG_BT_GATT_CLIENT=y
CONFIG_BT_GATT_SERVER=y
CONFIG_ZMK_BLE_PAIRING=y
